---
title: "Analyse des Salaires dans le Domaine de la Science des Données (2024)"
author:
  - "Wilson Fotsing"
  - "Coumba Diop"
  - "Anaïs Nikiema"
  - "Blaise-Pascal Guibony"
output: html_document
---

## Résumé

Dans ce projet, nous avons analysé les salaires des scientifiques de données en 2024, en nous basant sur un ensemble de données provenant de Kaggle, intitulé *DataScience Salaries 2024* (Delikkaya, 2024). L'objectif était de comprendre les facteurs qui influencent les salaires dans ce domaine en pleine croissance, tels que l'expérience, la localisation géographique, la taille de l'entreprise et les compétences techniques.

Le jeu de données utilisé contient des informations détaillées sur les salaires et ces différents facteurs. Nous avons commencé par vérifier les données pour supprimer les valeurs manquantes et rectifier les erreurs éventuelles dans les variables.
Une fois les données préparées, nous avons réalisé une analyse exploratoire pour mieux comprendre comment chaque facteur influence les salaires. Les techniques statistiques utilisées comprennent des analyses de régression pour examiner les relations entre les variables indépendantes et les salaires. Nous avons aussi utilisé des visualisations graphiques comme des diagrammes de dispersion et des histogrammes pour rendre les résultats plus accessibles et pour observer les tendances générales dans les données.

Les résultats de notre analyse révèlent entre autre, que **l’expérience professionnelle** influence de loin les salaires des scientifiques de données en raison de l'acquisition, au fil du temps, de compétences techniques avancées et de capacités stratégiques. Par ailleurs, **la localisation géographique** est également cruciale. Les scientifiques de données travaillant dans des villes comme San Francisco, Londres ou New York perçoivent des salaires bien plus élevés que ceux dans des régions moins densément peuplées. Cela est dû à la concentration d'entreprises technologiques et à une forte demande de talents dans ces zones. **La spécialisation technique**, notamment dans des domaines comme l'intelligence artificielle, l’apprentissage automatique et le traitement du langage naturel, impacte aussi les salaires. Les compétences dans ces technologies de pointe sont particulièrement recherchées par les entreprises. Enfin, **La taille des entreprises** joue un rôle important en ce sens qu'elles offrent d'autant plus de rémunérations compétitives qu'elles sont grandes. A contrario dans les startups et les petites entreprises, les rémunérations relativement moindres sont compensées une culture d’entreprise plus flexible et des opportunités de croissance rapide.

Au sortie de notre analyse, nous avons ainsi conclu que l’expérience professionnelle, la spécialisation technique, la localisation géographique, et la taille de l’entreprise sont des éléments déterminants pour définir les salaires des professionnels de la donnée. Concernant le facteur principal qui est l'expérience professionnelle, cette étude montre que les scientifiques de données expérimentés et ayant d'autres compétences comme l’intelligence artificielle, peuvent s’attendre à des rémunérations élevées, en particulier s’ils évoluent dans des grandes entreprises ou dans des régions à forte demande.

Quant aux jeunes professionnels ou ceux qui souhaitent s'orienter vers la science des données, il est recommandé de se concentrer sur l’acquisition de compétences techniques avancées et de viser des zones géographiques où la demande est forte. De plus, une expérience en entreprise, même dans des rôles juniors ou de stage, peut accélérer l'évolution salariale. Les entreprises devraient, quant à elles, prendre en compte ces facteurs dans leur stratégie de rémunération pour attirer et fidéliser les talents dans ce secteur concurrentiel.

## Présentation

Notre présentation est disponible [ici](presentation/presentation.html).